AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: Template to create the Lambda & EventBridge resources required by the cantrill.io-courses-scraper Serverless Application

Parameters:
  Environment:
    Description: Enter Dev or Prod. Default is Dev
    Type: String
    AllowedValues:
      - Dev
      - Prod
    Default: Dev

  ScheduleExpression:
    Description: Enter a scheduling expression (https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html)
    Type: String
    Default: cron(0 0,8,16 * * ? *)

Resources:
  CantrillCoursesScraperLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Environment:
        Variables:
          COURSES: "config_files/courses.json"
          DURATION_VARIANCE_PERCENTAGE: 5.0
          FORCED_MATCHES: "config_files/forced_matches.json"
          FUZZY_SET_MINIMUM_SCORE_MATCH: 0.7
          FUZZY_SET_INVALID_MATCHES: "config_files/fuzzyset_invalid_matches.json"
          SKIPPED_MATCHES: "config_files/skipped_matches.json"
          S3_BUCKET_NAME: !ImportValue
            "Fn::Sub": "CantrillCoursesScraperS3BucketName${Environment}"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Name:
              !Join [
                "",
                [
                  CantrillCoursesScraperLambdaFunctionScheduledEvent,
                  !Ref Environment,
                ],
              ]
            Schedule: !Ref ScheduleExpression
      FunctionName: !Join ["", [CantrillCoursesScraper, !Ref Environment]]
      Handler: app.lambdaHandler
      Role: !ImportValue
        "Fn::Sub": "CantrillCoursesScraperLambdaFunctionRoleArn${Environment}"
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 60
