AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: Template to create the Lambda & EventBridge resources required by the cantrill.io-courses-scraper Serverless Application

Parameters:
  Environment:
    Description: Enter Dev or Prod. Default is Dev
    Type: String
    AllowedValues:
      - Dev
      - Prod
    Default: Dev

  ScheduleExpression:
    Description: Enter a scheduling expression (https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html)
    Type: String
    Default: cron(0 0,8,16 * * ? *)

Resources:
  CantrillCoursesScraperLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Environment:
        Variables:
          COURSES: >-
            {
              "associate": [
                  {
                      "code": "dva-c01",
                      "color": "#2c77ea",
                      "title": "AWS Certified Developer - Associate",
                      "url": "https://learn.cantrill.io/p/aws-certified-developer-associate"
                  },
                  {
                      "code": "saa-c02",
                      "color": "#2c77ea",
                      "title": "AWS Certified Solutions Architect - Associate",
                      "url": "https://learn.cantrill.io/p/aws-certified-solutions-architect-associate-saa-c02"
                  },
                  {
                      "code": "soa-c02",
                      "color": "#2c77ea",
                      "title": "AWS Certified SysOps Administrator - Associate",
                      "url": "https://learn.cantrill.io/p/aws-certified-sysops-administrator-associate"
                  }
              ],
              "professional": [
                  {
                      "code": "sap-c01",
                      "color": "#3dcac0",
                      "title": "AWS Certified Solutions Architect - Professional",
                      "url": "https://learn.cantrill.io/p/aws-certified-solutions-architect-professional"
                  },
                  {
                      "code": "dop-c01",
                      "color": "#3DCAC0",
                      "title": "AWS Certified DevOps Engineer - Professional",
                      "url": "https://learn.cantrill.io/p/aws-certified-devops-engineer-professional"
                  }
              ],
              "specialty": [
                  {
                      "code": "ans-c01",
                      "color": "#4d27aa",
                      "title": "AWS Certified Advanced Networking - Specialty",
                      "url": "https://learn.cantrill.io/p/aws-certified-advanced-networking-specialty"
                  }
              ]
            }
          DURATION_VARIANCE_PERCENTAGE: 5.0
          FUZZY_SET_MINIMUM_SCORE_MATCH: 0.7
          FUZZY_SET_INVALID_MATCHES: ""
          LECTURES_SKIP_LIST: ""
          S3_BUCKET_NAME: !ImportValue
            "Fn::Sub": "CantrillCoursesScraperS3BucketName${Environment}"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Name:
              !Join [
                "",
                [
                  CantrillCoursesScraperLambdaFunctionScheduledEvent,
                  !Ref Environment,
                ],
              ]
            Schedule: !Ref ScheduleExpression
      FunctionName: !Join ["", [CantrillCoursesScraper, !Ref Environment]]
      Handler: app.lambdaHandler
      Role: !ImportValue
        "Fn::Sub": "CantrillCoursesScraperLambdaFunctionRoleArn${Environment}"
      MemorySize: 1024
      Runtime: nodejs14.x
      Timeout: 60
