AWSTemplateFormatVersion: 2010-09-09

Description: Template to create the S3 resources required by the cantrill.io-courses-scraper Serverless Application

Outputs:
  CantrillCoursesScraperS3BucketName:
    Description: The name of the S3 bucket
    Value: !Ref CantrillCoursesScraperS3Bucket
    Export:
      Name: !Join ["", [CantrillCoursesScraperS3BucketName, !Ref Environment]]

  CantrillCoursesScraperS3BucketArn:
    Description: The ARN of the S3 bucket
    Value: !GetAtt CantrillCoursesScraperS3Bucket.Arn
    Export:
      Name: !Join ["", [CantrillCoursesScraperS3BucketArn, !Ref Environment]]

  CantrillCoursesScraperS3BucketWebsiteURL:
    Description: The website endpoint of the S3 bucket
    Value: !GetAtt CantrillCoursesScraperS3Bucket.WebsiteURL

Parameters:
  Environment:
    Description: Enter Dev or Prod. Default is Dev
    Type: String
    AllowedValues:
      - Dev
      - Prod
    Default: Dev

  S3BucketName:
    Description: Enter the name of the S3 bucket
    Type: String

Resources:
  CantrillCoursesScraperS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName
      WebsiteConfiguration:
        IndexDocument: index.html

  CantrillCoursesScraperS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CantrillCoursesScraperS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              !Join ["", [!GetAtt CantrillCoursesScraperS3Bucket.Arn, /*]]
            Principal: "*"
